server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/school?characterEncoding=utf8&useSSL=false
    username: root
    password: 10040811yy
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

mybatis:
  configuration:  # setting配置
    auto-mapping-behavior: full
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  type-aliases-package: com.example.demo.entity # 配置别名
  mapper-locations: classpath:mapper/*.xml
#  mapper-locations: classpath:/com.example.springboot_course.mapper/*.xml # mapperxml位置

